# Generated by Django 5.1.6 on 2025-02-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='status_livraison',
            field=models.BooleanField(default=False, help_text='Cochez si la commande est sur place, sinon elle est livrée.', verbose_name='Type de commande'),
        ),
    ]
